org: punesoftwaretechnologies # 🔑 Replace this with your actual org name from Serverless Dashboard
app: express-app # 🔑 Replace this with any app name you set up (can be same as service)

service: express-app
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 1024
  timeout: 30
  environment:
    DB_URL: ${env:DB_URL}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  app:
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
